//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Routey.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Routey.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Route.
        /// </summary>
        internal static string DeleteRoute {
            get {
                return ResourceManager.GetString("DeleteRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Route.
        /// </summary>
        internal static string EndRoute {
            get {
                return ResourceManager.GetString("EndRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter route name....
        /// </summary>
        internal static string EnterRoute {
            get {
                return ResourceManager.GetString("EnterRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Page.
        /// </summary>
        internal static string MapPage {
            get {
                return ResourceManager.GetString("MapPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Routes:.
        /// </summary>
        internal static string PreviousRoutes {
            get {
                return ResourceManager.GetString("PreviousRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Information.
        /// </summary>
        internal static string RouteInfo {
            get {
                return ResourceManager.GetString("RouteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes History.
        /// </summary>
        internal static string RoutesHistory {
            get {
                return ResourceManager.GetString("RoutesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes Page.
        /// </summary>
        internal static string RoutesPage {
            get {
                return ResourceManager.GetString("RoutesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language:.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Page.
        /// </summary>
        internal static string SettingsPage {
            get {
                return ResourceManager.GetString("SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Route.
        /// </summary>
        internal static string StartRoute {
            get {
                return ResourceManager.GetString("StartRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Route.
        /// </summary>
        internal static string TrackRoute {
            get {
                return ResourceManager.GetString("TrackRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Map.
        /// </summary>
        internal static string ViewMap {
            get {
                return ResourceManager.GetString("ViewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
    }
}
